### ISSUE TITLE
default formatting

### ISSUE THREAD

**Issue by nickdesaulniers** [sustrik/libmill#35]
Also, we should consider adding a .clang-format file. These can be auto generated.  My recommendation is pick one that doesn't mess up the blame too much, and require PRs run all code through it before committing.

**Comment by reqshark** [comment]
that'd be cool. Would be simple enough to set that up in a travis.yml since it spins up a fresh Linux box for doing github CI. Oh plus they can do OSX automation. And if we did that much we might as well run a test suite at the same time. I like an automated smoke test for PRs before merging

@sustrik, would you consider using one of the free-to-open-source github integrations like Circleci or TravisCi? If so I could help get that going with a PR, that config is quickon either or both.

**Comment by sustrik** [comment]
Automated builds would be nice. Especially on OSX given that I don't own an OSX box myself.

**Comment by sustrik** [comment]
Automated build are up and running. Is there anything else to do with this ticket or should I close it?

**Comment by nickdesaulniers** [comment]
Where's the .clang-format file? As a contributor, how do I know which format to use for my code?

**Comment by sustrik** [comment]
No progress here for a long time. If anyone wants to contribute the formatting file, they are welcome. For now, I am closing the ticket.
